package presentacion.vistas.vistaModeloOrdenador;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import negocio.modeloOrdenador.TDepartamentoModeloOrdenador;
import negocio.modeloOrdenador.TModeloOrdenador;
import presentacion.comandos.listadecomandos.ListaComandos;
import presentacion.controlador.Controlador;

@SuppressWarnings("serial")
public class ModeloOrdenadorGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ModeloOrdenadorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                       
    private void initComponents() {

        jLabelIDModelo = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelAntiguedad = new javax.swing.JLabel();
        jLabelActivo = new javax.swing.JLabel();
        jLabelGarantia = new javax.swing.JLabel();
        jLabelIDDepartamento = new javax.swing.JLabel();
        jTextFieldIDModelo = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldAntiguedad = new javax.swing.JTextField();
        jTextFieldGarantia = new javax.swing.JTextField();
        jTextFieldIDDepartamento = new javax.swing.JTextField();
        jCheckBoxActivo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonAlta = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jTextArea.setEditable(false);

        jLabelIDModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIDModelo.setText("ID MODELO:");

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelo.setText("MODELO:");

        jLabelAntiguedad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAntiguedad.setText("ANTIGÜEDAD:");

        jLabelActivo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelActivo.setText("ACTIVO:");

        jLabelGarantia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelGarantia.setText("GARANTÍA:");

        jLabelIDDepartamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelIDDepartamento.setText("ID DEPARTAMENTO:");

        
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jButtonAlta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAlta.setText("ALTA");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonBaja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBaja.setText("BAJA");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConsultar.setText("AÑADIR DEPARTAMENTO");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarMODepartamentoActionPerformed(evt);
            }
        });

        jButtonListar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonListar.setText("ELIMINAR DEPARTAMENTO");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarMODepartamentoActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonModificar.setText("CANTIDAD TOTAL");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMantenimientoActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelIDDepartamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldIDDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAntiguedad)
                                            .addComponent(jLabelGarantia)
                                            .addComponent(jLabelActivo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxActivo)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldIDModelo)
                                                .addComponent(jTextFieldModelo)
                                                .addComponent(jTextFieldAntiguedad)
                                                .addComponent(jTextFieldGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelModelo)
                                .addGap(193, 193, 193))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelIDModelo)
                                .addGap(177, 177, 177)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBaja)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIDModelo)
                            .addComponent(jTextFieldIDModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAntiguedad)
                            .addComponent(jTextFieldAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelActivo)
                            .addComponent(jCheckBoxActivo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelGarantia)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelIDDepartamento)
                                    .addComponent(jTextFieldIDDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlta)
                    .addComponent(jButtonBaja)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonListar)
                    .addComponent(jButtonModificar))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    protected void jButtonRetirarMODepartamentoActionPerformed(ActionEvent evt) {
    	if(jTextFieldIDModelo.getText().isEmpty()||jTextFieldIDDepartamento.getText().isEmpty() ){
			JOptionPane.showMessageDialog(this, "Por favor indique el id del Modelo, id de Departamento", "Error", JOptionPane.ERROR_MESSAGE);
			
		}else{
			try {
				int modelo=Integer.parseInt(jTextFieldIDModelo.getText());
				int departamento=Integer.parseInt(jTextFieldIDDepartamento.getText());
				
				
				if(modelo<=0){
					JOptionPane.showMessageDialog(this, "El id de modelo ordenador debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);
				
				}
				else if(departamento <= 0){
					JOptionPane.showMessageDialog(this, "El id departamento debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);	
				}else{
					Controlador.getInstance().run(ListaComandos.RETIRARMODEPARTAMENTO, 
							new TDepartamentoModeloOrdenador(modelo, departamento, 0));
					limpiarComponentes();
				}
				
				
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Por favor asigne los campos correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
			}
			
		}
    	
    
		
	}

	protected void jButtonAsignarMODepartamentoActionPerformed(ActionEvent evt) {
		
		if(jTextFieldIDModelo.getText().isEmpty()||jTextFieldGarantia.getText().isEmpty()||jTextFieldIDDepartamento.getText().isEmpty() ){
			JOptionPane.showMessageDialog(this, "Por favor indique el id del Modelo, id de Departamento y años de garantia", "Error", JOptionPane.ERROR_MESSAGE);
			
		}else{
			try {
				int IDModelo=Integer.parseInt(jTextFieldIDModelo.getText());
				int IDDepartamento=Integer.parseInt(jTextFieldIDDepartamento.getText());
				int garantia=Integer.parseInt(jTextFieldGarantia.getText());
				
				if(IDModelo<=0){
					JOptionPane.showMessageDialog(this, "El id de modelo ordenador debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);
				}else if(garantia <= 0){
					JOptionPane.showMessageDialog(this, "La garantia de Modelo Ordenador asignados debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);	
				}
				else if(IDDepartamento <= 0){
					JOptionPane.showMessageDialog(this, "El id departamento debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);	
				}else{
					Controlador.getInstance().run(ListaComandos.ASIGNARMODEPARTAMENTO,
		    				new TDepartamentoModeloOrdenador(IDModelo, IDDepartamento, garantia));
																										
					limpiarComponentes();
				}
				
				
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Por favor asigne los campos correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
			}
			
		}
		
		
	}

	private void limpiarComponentes(){
    	jTextArea.setText("");
    	jTextFieldAntiguedad.setText("");
    	jTextFieldGarantia.setText("");
    	jTextFieldIDDepartamento.setText("");
    	jTextFieldIDModelo.setText("");
    	jTextFieldModelo.setText("");
    	jCheckBoxActivo.setSelected(false);
    
    }
    
    public void mensaje(String mensaje, String status){
	   	if(status=="Exito"){
		   JOptionPane.showMessageDialog(this, mensaje, status, JOptionPane.INFORMATION_MESSAGE);
	   	}
	   	else if(status=="Error"){
		   JOptionPane.showMessageDialog(this, mensaje, status, JOptionPane.ERROR_MESSAGE);
	   	}
    }
    
    protected void jButtonSalirActionPerformed(ActionEvent evt) {
    	limpiarComponentes();
		Controlador.getInstance().run(ListaComandos.CERRARVISTAMODELOORDENADOR, null);
		
	}

	protected void jButtonBajaActionPerformed(ActionEvent evt) {
		if (jTextFieldIDModelo.getText().isEmpty()){
    		JOptionPane.showMessageDialog(this, "Por favor indica el id del Modelo Ordenador.", "Error", JOptionPane.ERROR_MESSAGE);
    	} else {
    		try {
				int id = Integer.parseInt(jTextFieldIDModelo.getText());
				if (id <= 0) {
					JOptionPane.showMessageDialog(this, "El campo ID debe ser un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
				} else {
					Controlador.getInstance().run(ListaComandos.BAJAMODELOORDENADOR, id);
					limpiarComponentes();
				}
			}catch(NumberFormatException e) {
				JOptionPane.showMessageDialog(this, "El ID del departamento debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
			}
    	}
		
	}

	protected void jButtonAltaActionPerformed(ActionEvent evt) {
		try {
			String modelo = jTextFieldModelo.getText();
			int antiguedad = Integer.parseInt(jTextFieldAntiguedad.getText());
						
			//Comprobar que los campos generales de empleado tienen informacion
			if (jTextFieldModelo.getText().isEmpty() ||jTextFieldAntiguedad.getText().isEmpty() 
				//|| jTextFieldCantidad.getText().isEmpty() 
			){
				JOptionPane.showMessageDialog(this, "Por favor, rellena los campos del Modelo Ordenador", "Error",
						JOptionPane.ERROR_MESSAGE);
			} 
			//Comprueba que el ID de Departamento este en el rango
			else if(antiguedad <= 0){
				JOptionPane.showMessageDialog(this, "La antigüedad del Modelo Ordenador debe ser un número mayor que cero", "Error",JOptionPane.ERROR_MESSAGE);	
			}
			else {
				
				//El usuario ha ingresado informacion valida
				TModeloOrdenador tModelo = new TModeloOrdenador(modelo, antiguedad, true);
				Controlador.getInstance().run(ListaComandos.ALTAMODELOORDENADOR, tModelo);
				limpiarComponentes();
			
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Por favor rellene los campos de Modelo Ordenador  correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
		}
		
		limpiarComponentes();
		
	}

	private void jButtonMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	JOptionPane.showMessageDialog(this, "Lo sentimos, este apartado esta en mantenimiento", "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloOrdenadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloOrdenadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloOrdenadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloOrdenadorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloOrdenadorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxActivo;
    private javax.swing.JLabel jLabelActivo;
    private javax.swing.JLabel jLabelAntiguedad;
    private javax.swing.JLabel jLabelGarantia;
    private javax.swing.JLabel jLabelIDDepartamento;
    private javax.swing.JLabel jLabelIDModelo;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextFieldAntiguedad;
    private javax.swing.JTextField jTextFieldGarantia;
    private javax.swing.JTextField jTextFieldIDDepartamento;
    private javax.swing.JTextField jTextFieldIDModelo;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration                   
}

