	package presentacion.vistas.vistaDepartamento;

import java.awt.event.ActionEvent;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

import negocio.departamento.TDepartamento;
import presentacion.comandos.listadecomandos.ListaComandos;
import presentacion.controlador.Controlador;

@SuppressWarnings("serial")
public class DepartamentoGUI extends javax.swing.JFrame {
	    /**
	     * Creates new form Departamento
	     */
	    public DepartamentoGUI() {
	        initComponents();
	    }
	
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */

	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	
	        jLabelID = new javax.swing.JLabel();
	        jLabelNombre = new javax.swing.JLabel();
	        jLabelCategoria = new javax.swing.JLabel();
	        jLabelActivo = new javax.swing.JLabel();
	        jTextFieldID = new javax.swing.JTextField();
	        jTextFieldNombre = new javax.swing.JTextField();
	        jTextFieldCategoria = new javax.swing.JTextField();
	        jCheckBoxActivo = new javax.swing.JCheckBox();
	        jTextArea = new javax.swing.JTextArea();
	        jScrollPane =  new JScrollPane(jTextArea);
	        jScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
	        jButtonAlta = new javax.swing.JButton();
	        jButtonBaja = new javax.swing.JButton();
	        jButtonModificar = new javax.swing.JButton();
	        jButtonListar = new javax.swing.JButton();
	        jButtonMostrar = new javax.swing.JButton();
	        jButtonSueldo = new javax.swing.JButton();
	        jButtonSalir = new javax.swing.JButton();
	
	        jTextArea.setEditable(false);
	        
	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        
	        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 14));
	        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabelID.setText("ID DEPARTAMENTO:");
	
	        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14));
	        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabelNombre.setText("NOMBRE:");
	
	        jLabelCategoria.setFont(new java.awt.Font("Tahoma", 1, 14));
	        jLabelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabelCategoria.setText("CATEGORIA: ");
	
	        jLabelActivo.setFont(new java.awt.Font("Tahoma", 1, 14));
	        jLabelActivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabelActivo.setText("ACTIVO:");
	
	       
	        jTextArea.setColumns(20);
	        jTextArea.setRows(5);
	
	        jButtonAlta.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonAlta.setText("ALTA");
	        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonAltaActionPerformed(evt);
	            }
	        });
	
	        jButtonBaja.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonBaja.setText("BAJA");
	        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonBajaActionPerformed(evt);
	            }
	        });
	
	        jButtonModificar.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonModificar.setText("MODIFICAR");
	        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonModificarActionPerformed(evt);
	            }
	        });
	
	
	        jButtonListar.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonListar.setText("LISTAR");
	        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonListarActionPerformed(evt);
	            }
	        });
	
	        jButtonMostrar.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonMostrar.setText("MOSTRAR");
	        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonMostrarActionPerformed(evt);
	            }
	        });
	
	        jButtonSueldo.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonSueldo.setText("SUELDO TOTAL DE DEPARTAMENTO");
	        jButtonSueldo.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonSueldoActionPerformed(evt);
	            }
	        });
	        
	        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 11));
	        jButtonSalir.setText("SALIR");
	        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButtonSalirActionPerformed(evt);
	            }
	        });
	        
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(33, 33, 33)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
	                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(jLabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(jLabelActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addGap(18, 18, 18)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jCheckBoxActivo)
	                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(42, 42, 42)
	                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(21, 21, 21)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
	                    .addComponent(jButtonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addGap(18, 18, 18)
	                .addComponent(jButtonBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButtonSueldo)
	                .addGap(35, 35, 35))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jTextFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
	                            .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGap(18, 18, 18)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(19, 19, 19)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                            .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabelActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jCheckBoxActivo)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(37, 37, 37)
	                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addGap(40, 40, 40)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButtonAlta)
	                    .addComponent(jButtonBaja)
	                    .addComponent(jButtonModificar)
	                    .addComponent(jButtonListar)
	                    .addComponent(jButtonMostrar)
	                    .addComponent(jButtonSueldo))
	                .addGap(18, 18, 18)
	                .addComponent(jButtonSalir)
	                .addContainerGap(27, Short.MAX_VALUE))
	        );
	
	        pack();
	    }// </editor-fold>                        
	
	    //Rellenar el id
	    public void setIdField(int id){
	    	String idAux = Integer.toString(id);
	    	jTextFieldID.setText(idAux);
	    }
	  
	    //Mostrar una lista de departamentos
	    public void setDepartamentos(List<TDepartamento> lista){
	    	String temp;
	    	for(int i = 0; i < lista.size(); i++){
	    		temp = lista.get(i).toString();
	    		jTextArea.append(temp + "\n");
	    	}
	    }
	    
	    
	    public void pintarMostrarDepartamento(TDepartamento dep){
	    	jTextArea.setText(dep.toString());
	    }
	    
	    public void setDepartamentoSueldo(TDepartamento dpto){
	    	jTextArea.setText("");
	    	jTextArea.append("ID DEPARTAMENTO: "+dpto.getIdDepartamento()+"\n");
	    	jTextArea.append("NOMBRE: "+dpto.getNombre()+"\n");
	    	jTextArea.append("CATEGORIA: "+dpto.getCategoria()+"\n");
	    	jTextArea.append("SUELDO DEPARTAMENTO: "+dpto.getTotalSueldoDepartamento()+"\n");
	    	//
	    }
	   
	    
	    public void mensaje(String mensaje, String status){
		   	if(status=="Exito"){
			   JOptionPane.showMessageDialog(this, mensaje, status, JOptionPane.INFORMATION_MESSAGE);
		   	}
		   	else if(status=="Error"){
			   JOptionPane.showMessageDialog(this, mensaje, status, JOptionPane.ERROR_MESSAGE);
		   	}
	    }	    
	    
	    protected void jButtonSalirActionPerformed(ActionEvent evt) {
	    	limpiarComponentes();
	    	Controlador.getInstance().run(ListaComandos.CERRARVISTADEPARTAMENTO,null);
		}


		protected void jButtonSueldoActionPerformed(ActionEvent evt) {
			
			//Comprobamos que el campo ID no esta vacio
			if(jTextFieldID.getText().isEmpty()){
				JOptionPane.showMessageDialog(this, "Indica el ID del departamento", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				try{
					//Check if ID field has int format
					int id =Integer.parseInt(jTextFieldID.getText());
					
					if(id<=0){
						JOptionPane.showMessageDialog(this, "El ID del Departamento debe ser un numero entero positivo.", "Error", JOptionPane.ERROR_MESSAGE);
					}else{
						
						Controlador.getInstance().run(ListaComandos.SUELDODEPARTAMENTO, id);
					}
					
					
					
				}catch(NumberFormatException e) {
					JOptionPane.showMessageDialog(this, "Indica el ID del departamento corretamente ", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
			
			
			
			
			
			
		}

		protected void jButtonMostrarActionPerformed(ActionEvent evt) {
			//Comprueba que eL ID del Departamento no este vacio
			if(jTextFieldID.getText().isEmpty()){
				JOptionPane.showMessageDialog(this, "Indica el ID del departamento", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				try{
					
					//Check if ID field has int format
					int idDep = Integer.parseInt(jTextFieldID.getText());
					
					//Comprueba que el ID del Departamento sea positivo
					if(idDep <= 0) {
						JOptionPane.showMessageDialog(this, "El campo ID debe ser un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
					} else {
						limpiarComponentes();
						Controlador.getInstance().run(ListaComandos.CONSULTARDEPARTAMENTO, idDep);
					}
					
					
				}catch(NumberFormatException e) {
					JOptionPane.showMessageDialog(this, "Indica el ID del departamento correctamente", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}

		protected void jButtonModificarActionPerformed(ActionEvent evt) {
			if(jTextFieldCategoria.getText().isEmpty() || jTextFieldNombre.getText().isEmpty()) {
				JOptionPane.showMessageDialog(this, "Rellena los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				try {
					String nombre = jTextFieldNombre.getText();
					String categoria = jTextFieldCategoria.getText();
					TDepartamento tDep = new TDepartamento(nombre, categoria, true);
					Controlador.getInstance().run(ListaComandos.MODIFICARDEPARTAMENTO, tDep);
					limpiarComponentes();
					
				}catch(NumberFormatException e) {
					JOptionPane.showMessageDialog(this, "Indica el ID del departamento correctamente", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
			
		}

		private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {                                            
			if(jTextFieldCategoria.getText().isEmpty() || jTextFieldNombre.getText().isEmpty()) {
				JOptionPane.showMessageDialog(this, "Rellena los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				String nombre = jTextFieldNombre.getText();
				String categoria = jTextFieldCategoria.getText();
				TDepartamento tDep = new TDepartamento(-1, nombre, categoria, true);
				
				Controlador.getInstance().run(ListaComandos.ALTADEPARTAMENTO, tDep);
				limpiarComponentes();
			}
	    }                                           
	
	    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {                                            
	    	if (jTextFieldID.getText().isEmpty()){
	    		JOptionPane.showMessageDialog(this, "Por favor indica el id del departamento.", "Error", JOptionPane.ERROR_MESSAGE);
	    	} else {
	    		try {
					int id = Integer.parseInt(jTextFieldID.getText());
					if (id <= 0) {
						JOptionPane.showMessageDialog(this, "El campo ID debe ser un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
					} else {
						Controlador.getInstance().run(ListaComandos.BAJADEPARTAMENTO, id);
						limpiarComponentes();
					}
				}catch(NumberFormatException e) {
					JOptionPane.showMessageDialog(this, "Indica el ID del departamento correctamente", "Error", JOptionPane.ERROR_MESSAGE);
				}
	    	}
	    }                                           
	
	    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        limpiarComponentes();
	        Controlador.getInstance().run(ListaComandos.LISTARDEPARTAMENTO, null);
	    }                                             
	
	    private void limpiarComponentes(){
	    	this.jCheckBoxActivo.setSelected(false);
	    	this.jTextArea.setText("");
	    	this.jTextFieldCategoria.setText("");
	    	this.jTextFieldID.setText("");
	    	this.jTextFieldNombre.setText("");
	    }
	    
	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(DepartamentoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	
	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new DepartamentoGUI().setVisible(true);
	            }
	        });
	    }
	
	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButtonAlta;
	    private javax.swing.JButton jButtonBaja;
	    private javax.swing.JButton jButtonListar;
	    private javax.swing.JButton jButtonModificar;
	    private javax.swing.JButton jButtonMostrar;
	    private javax.swing.JButton jButtonSalir;
	    private javax.swing.JButton jButtonSueldo;
	    private javax.swing.JCheckBox jCheckBoxActivo;
	    private javax.swing.JLabel jLabelActivo;
	    private javax.swing.JLabel jLabelCategoria;
	    private javax.swing.JLabel jLabelID;
	    private javax.swing.JLabel jLabelNombre;
	    private javax.swing.JScrollPane jScrollPane;
	    private javax.swing.JTextArea jTextArea;
	    private javax.swing.JTextField jTextFieldCategoria;
	    private javax.swing.JTextField jTextFieldID;
	    private javax.swing.JTextField jTextFieldNombre;
	    // End of variables declaration 
}
